{{- range $index := until 3 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "hbase-master-pv-{{  $index  }}"
  labels:
    pv: "hbase-master-pv"
spec:
  capacity:
    storage: {{ $.Values.master.storage }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hbase-localpv
  local:
    path: {{ $.Values.master.nnDir }}
  nodeAffinity:
{{ toYaml $.Values.master.nodeAffinity|indent 4 }}

{{- end }}
