---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ldap-cluster-admin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: Group
    name: k8s
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ldap-test
  namespace: test
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ldap-test 
  namespace: test
subjects:
- kind: Group
  name: test
  apiGroup: ""
roleRef:
  kind: Role
  name: ldap-test
  apiGroup: ""
---

