apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: testvol
      mountPath: /data
  volumes:
  - name: testvol
    persistentVolumeClaim:
      claimName: test
