---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loginapp
  namespace: kube-system
data:
  config.yaml: |
    name: "Kubernetes Auth"
    listen: "0.0.0.0:5555"
    oidc:
      client:
        id: "loginapp"
        secret: ZXhhbXBsZS1hcHAtc2VjcmV0
        redirect_url: "https://loginapp.5ik8s.com/callback"
      issuer:
        root_ca: "/etc/ssl/ca.crt"
        url: "https://dex.5ik8s.com"
      extra_scopes:
        - groups
      offline_as_scope: false
    tls:
      enabled: false
    #  cert: example/ssl/cert.pem
    #  key: example/ssl/key.pem
    log:
      level: Debug
      format: json
    clusters:
      - name: k8s
        server: https://192.168.65.91:6443
        certificate-authority: |
          -----BEGIN CERTIFICATE-----
          MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
          cm5ldGVzMB4XDTE5MDcyNTA4MDM1OFoXDTI5MDcyMjA4MDM1OFowFTETMBEGA1UE
          AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAN2A
          ZvCzBxKfJ2xV48ZHtCPOvWRqJJzrKhJsV28SyYqvDDWCbF0A+lq//dt00P9UgnpP
          W1h+Tvbq2Xi8k1Y4U9VQzvQdoimOpJGvNCS0j6K9ciZ6UQuKN0I1mnhywKKFXjvX
          +FaPHg0RH23jJPGORENIVbJs5BweRRWsik9Cvx4CSRw8BDUCziSIGJkliWMt8Jqh
          CV2F/nh8/k6fjYhFLL43s2Q0x0jwPrg2uRO5u/2N+6ra4R9m/7piHS90RKbsJcOG
          iMyrFWGbLWA94BaTTWswud5eTTkLHmnoV+d2ILPrPZq4BQMHfdK0uk/OvLxdl6ze
          yfN1HFHtEtq7vfJQFoMCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
          /wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAKfK1hSz9/VSu8/3EmXPxkNu5Z07
          v+HlPmT5bmzYWRdAEDzlq6l6vBQRE4u0EjCnOpXL9lWfe2vnq4oq309v+Su9Yaur
          RZx7eDQYnPzq2i0OTwErA78SYz/ChkokRACZExudo9ADKIXN2x4l8AbawvravFv4
          aS7FjZIhccWhHG9j/G33ptwu5GDd/T1lhtfpPt4AxsD+F5GzPlIGWcX7FjufQRcs
          HEeAJQc7cmcAw+xyGsWgj5ushQbYMQUogGvFADC4YhG7BPocBm6VcMPMh5nYHyaB
          0NniKlP9NZvM2X6Bf4JKKU9phaozCCT/eYmwKGX/hIy3Po/kdgiFFetLgag=
          -----END CERTIFICATE-----
        insecure-skip-tls-verify: false
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loginapp
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: loginapp
    spec:
      containers:
      - image: quay.io/fydrah/loginapp:2.7.0
        args:
        - serve
        - /app/config.yaml
        name: loginapp
        volumeMounts:
        - name: ca
          mountPath: /etc/ssl/
        - name: config
          mountPath: /app/
      volumes:
      - name: ca
        configMap:
          name: 5ik8s.com-ca
          items:
          - key: ca.crt
            path: ca.crt
      - name: config
        configMap:
          name: loginapp
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: loginapp
  namespace: kube-system
spec:
  ports:
  - name: loginapp
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: loginapp

