apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Retain
parameters:
  gidMax: "50000"
  gidMin: "40000"
  resturl: http://192.168.65.26:8083
  volumetype: replicate:3
  restauthenabled: "true"
  restuser: "admin"
  restuserkey: "ndaX0cDKeuzs"
