apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  annotations:
    volume.beta.kubernetes.io/storage-class: "glusterfs"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
