{{- if and .Values.global.gitaly.enabled (not .Values.global.praefect.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab.gitaly.serviceName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.serviceLabels" . | nindent 4 }}
  annotations:
  {{- if .Values.metrics.enabled }}
    gitlab.com/prometheus_scrape: "true"
    gitlab.com/prometheus_port: "{{ .Values.metrics.metricsPort }}"
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.metricsPort }}"
  {{- end }}
    {{- include "gitlab.serviceAnnotations" . | nindent 4 }}
{{ include (print $.Template.BasePath "/_service_spec.yaml") . }}
{{- end }}
