apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-data
  namespace: kube-system
  labels:
    app: ldap
spec:
  storageClassName: default-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-config
  namespace: kube-system
  labels:
    app: ldap
spec:
  storageClassName: default-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"

